# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=127, unique=True, verbose_name='Identifier')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
